/**
 * Mock datas. 4Alabs oriented any sector images
 * @author Mehmet FASIL
 */

export const Images = {
  dollar: require("@assets/images/dollar.png"),
  dollar2: require("@assets/images/dollar2.png"),
  lira: require("@assets/images/lira.png"),
  table: require("@assets/images/table.png"),
  bg: require("@assets/images/bg.png"),
  cube: require("@assets/images/cube.png"),
  cardBg2: require("@assets/images/card-bg-2.png"),
  cardBg: require("@assets/images/card-bg.png"),
  logo: require("@assets/images/logo.png"),
  companyMenuBg: require("@assets/images/company-menu-bg.png"),
  logoBg: require("@assets/images/logo-bg.png"),
  slide: require("@assets/images/slide.png"),
  avata1: require("@assets/images/avata-01.jpeg"),
  danger: require("@assets/images/danger.png"),
  avata2: require("@assets/images/avata-02.jpeg"),
  avata3: require("@assets/images/avata-03.jpeg"),
  avata4: require("@assets/images/avata-04.jpeg"),
  element1_1: require("@assets/images/element1-1.jpg"),
  element1_2: require("@assets/images/element1-2.jpg"),
  element1_3: require("@assets/images/element1-3.jpg"),
  element1_4: require("@assets/images/element1-4.jpg"),
  element1_5: require("@assets/images/element1-5.jpg"),
  element2_1: require("@assets/images/element2-1.jpg"),
  element2_2: require("@assets/images/element2-2.jpg"),
  element2_3: require("@assets/images/element2-3.jpg"),
  element2_4: require("@assets/images/element2-4.jpg"),
  element2_5: require("@assets/images/element2-5.jpg"),
  element2_6: require("@assets/images/element2-6.jpg"),
  element2_7: require("@assets/images/element2-7.jpg"),
  element2_8: require("@assets/images/element2-8.jpg"),
  element3_1: require("@assets/images/element3-1.jpg"),
  element3_2: require("@assets/images/element3-2.jpg"),
  element3_3: require("@assets/images/element3-3.jpg"),
  element3_4: require("@assets/images/element3-4.jpg"),
  element3_5: require("@assets/images/element3-5.jpg"),
  element3_6: require("@assets/images/element3-6.jpg"),
  profile1: require("@assets/images/profile-1.jpg"),
  profile2: require("@assets/images/profile-2.jpg"),
  profile3: require("@assets/images/profile-3.jpg"),
  profile4: require("@assets/images/profile-4.jpg"),
  profile5: require("@assets/images/profile-5.jpg"),
  profile6: require("@assets/images/profile-6.jpg"),
  profile7: require("@assets/images/profile-7.jpg"),
  profile8: require("@assets/images/profile-8.jpg"),
  element4_1: require("@assets/images/element4_1.jpg"),
  element4_2: require("@assets/images/element4_2.jpg"),
  element4_3: require("@assets/images/element4_3.jpg"),
  element4_4: require("@assets/images/element4_4.jpg"),
  element4_5: require("@assets/images/element4_5.jpg"),
  element4_6: require("@assets/images/element4_6.jpg"),
  element4_7: require("@assets/images/element4_7.jpg"),
  element4_8: require("@assets/images/element4_8.jpg"),
  element4_9: require("@assets/images/element4_9.jpg"),
  element5_1: require("@assets/images/element5_1.jpg"),
  element5_2: require("@assets/images/element5_2.jpg"),
  background1: require("@assets/images/background_01.jpg"),
  background2: require("@assets/images/background_02.jpg"),
  background3: require("@assets/images/background_03.jpg"),
  background4: require("@assets/images/background_04.jpg"),
  background5: require("@assets/images/background_05.png"),
  banner1: require("@assets/images/banner-1.jpg"),
  group1: require("@assets/images/group-3.png"),
  group2: require("@assets/images/group-2.png"),
  group3: require("@assets/images/group-1.png"),
  element6_1: require("@assets/images/element6_1.jpg"),
  element7_1: require("@assets/images/element7_1.png"),
  yassiUrun: require("@assets/images/yassi.jpg"),
  uzunUrun: require("@assets/images/uzun.jpg"),
  module_yonetim: require("@assets/images/module_yonetim.png"),
  module_uretim: require("@assets/images/module_uretim.png"),
  module_muhasebe: require("@assets/images/module_muhasebe.png"),
  module_ik: require("@assets/images/module_ik.png"),
  module_cagri: require("@assets/images/module_cagri.png"),
  module_raporlama: require("@assets/images/module_raporlama.png"),
  module_analiz: require("@assets/images/module_analiz.png"),
  module_teknik: require("@assets/images/module_teknik.png"),
  headerBg: require("@assets/images/header-bg.png"),
  banner: require("@assets/images/banner.png"),
  urunKatalog1: require("@assets/images/urun-katalog-1.png"),
  urunKatalog2: require("@assets/images/urun-katalog-2.png"),
  uyariBanner: require("@assets/images/uyari-banner.png"),
  contactBanner: require("@assets/images/contact-banner.png"),
  //sertificate:require("@assets/images/sertificate.png"),

  sertificate: require("@assets/images/sertificate.png")
};
